const PURPLE_PLAYER = {
    AVAILABLE: 4,
    PLACED: 0,
    MILLPIECES: 0,
    // POSITIONS: []
};

const YELLOW_PLAYER = {
    AVAILABLE: 4,
    PLACED: 0,
    MILLPIECES: 0,
    // POSITIONS: []
};

const PURPLE_TURN = 0;
const YELLOW_TURN = 1;

export { PURPLE_PLAYER, YELLOW_PLAYER, PURPLE_TURN, YELLOW_TURN };

